### ISSUE TITLE
【BUG】布局大小组件编码问题

### ISSUE THREAD

**Issue by samho2008** [yangzongzhuan/RuoYi-Cloud-Vue3#10]
其他组件用的都是 UTF-8 编码，但是这个组件用的是 GB2312 导致了乱码问题
![image](https://user-images.githubusercontent.com/92196261/183581073-3affc9a8-9ff3-4d0b-b0eb-632446a293cd.png)

**Comment by yangzongzhuan** [comment]
OK，你来这里PR吧， https://gitee.com/y_project/RuoYi-Cloud/pulls

**Comment by elarbor** [comment]
> OK，你来这里PR吧， https://gitee.com/y_project/RuoYi-Cloud/pulls
我提了一些PR
<img width="780" alt="image" src="https://github.com/user-attachments/assets/57acee47-5373-4768-a3da-b0bc112dbf11">
