### ISSUE TITLE
你好 vite构建的, 怎么在浏览器直接访问public下的静态资源呢

### ISSUE THREAD

**Issue by icu-start** [yangzongzhuan/RuoYi-Cloud-Vue3#12]
你好, 我使用的是您仓库的Vite+vue3构建的前端, 但是我怎么在浏览器访问public下的资源呢 我在public下放入了 pdfjs的插件包,  无法访问到public下的.html

**Comment by yangzongzhuan** [comment]
参考官方的演示地址 http://vue.ruoyi.vip/html/ie.html
