### ISSUE TITLE
captchaImage,????:404 NOT_FOUND

### ISSUE THREAD

**Issue by yuning1227** [yangzongzhuan/RuoYi-Cloud-Vue3#21]
RuoYi-Cloud-Vue3 接  RuoYi-Cloud-v3.6.4 报 captchaImage,????:404 NOT_FOUND 验证码加载不上？大佬都帮说一下怎么处理吗？

**Comment by Al1star** [comment]
拉错项目了吧，我刚好克隆成了RuoYi Vue项目，和你的问题表现是一样的

**Comment by yangzongzhuan** [comment]
嗯，很明显的拉错项目了，captchaImage是不分离版本里面的，微服务是RuoYi-Cloud RuoYi-Cloud-Vue3
