### ISSUE TITLE
表单构建的代码好像不见了？

### ISSUE THREAD

**Issue by killermiter8** [yangzongzhuan/RuoYi-Cloud-Vue3#22]
请问表单构建的代码是还没写，还是不见了？
![微信截图_20240821090125](https://github.com/user-attachments/assets/0abf00c2-1a95-409c-a75d-3643d586257e)

**Comment by yangzongzhuan** [comment]
已经更新了，拉取最新的代码即可。

**Comment by elarbor** [comment]
平台所有不在菜单栏显示的内页，例如表单页、详情页，都要手动在`dynamicRoutes`写死吗？
<img width="1920" alt="image" src="https://github.com/user-attachments/assets/40745be3-c0dc-48c4-8594-77fd9d177f2f">
