### ISSUE TITLE
Cron表达式的年份选择逻辑bug

### ISSUE THREAD

**Issue by zjg2114** [yangzongzhuan/RuoYi-Cloud-Vue3#23]
bug1:
代码地址:https://github.com/yangzongzhuan/RuoYi-Cloud-Vue3/blob/master/src/components/Crontab/year.vue#L100-L101
<img width="527" alt="image" src="https://github.com/user-attachments/assets/a9e28cf8-aba0-4455-ac03-46f0bc9a2937">
数组的取值取反了

bug2:
代码地址:https://github.com/yangzongzhuan/RuoYi-Cloud-Vue3/blob/master/src/components/Crontab/year.vue#L87
<img width="884" alt="image" src="https://github.com/user-attachments/assets/3e24efe8-0c9e-47fe-919d-1b64595a9be2">
年份表达式中的computed计算属性 无法被watch监听,切换radio时 无法触发父组件的update

**Comment by yangzongzhuan** [comment]
请提供具体的步骤和相关能复现问题的流程
