### ISSUE TITLE
登录页面状态码请求成功，但是返回500

### ISSUE THREAD

**Issue by 17722797729** [yangzongzhuan/RuoYi-Cloud-Vue3#8]
看了一下Cloud非VUE3版本的前端，，登录时请求路径明显不一致。

![2AC42681-417F-4f03-A0D9-06462D2DFAB1](https://user-images.githubusercontent.com/43561533/167988562-332ac1b3-183b-4221-94bc-75c694043663.png)
![9D138D8E-9E72-423c-8280-24972845136A](https://user-images.githubusercontent.com/43561533/167988622-f31fff54-e3e1-4a78-ac85-ee70eaeebaa5.png)

**Comment by LishenZz** [comment]
cloud ==> https://github.com/yangzongzhuan/RuoYi-Cloud-Vue3

**Comment by yangzongzhuan** [comment]
你用最新的版本代码去试试，这个接口有修改过，前缀是/auth
参考示例 https://github.com/yangzongzhuan/RuoYi-Cloud-Vue3/blob/master/src/api/login.js
